In [5]:

date='''"2022-02-19 00:00:00.000000"'''

import pyomo.environ as pyo
# install glpk in pyomo/solvers/ folder.
import pandas as pd

import sqlite3

cnx = sqlite3.connect('/Users/kultiginbozdemir/Documents/GitHub/op_room_opt/Website/test.db') # change the path

#class Solve_Problem:


query = ''.join(['SELECT * FROM user_entries WHERE operation_date==',str(date)])# change name of the table.  save them with date in db. 

basket = pd.read_sql(query,cnx)
basket.index=basket.id

query_dep_cap =''.join(['SELECT * FROM department_info WHERE date==',str(date)]) # table of department capacities
dep_df = pd.read_sql_query(query_dep_cap, cnx)# departments
dep_df.index=dep_df.department_name
dep_df['department_capacity']=dep_df['department_capacity'].astype(int)
 


query_op_cap = ''.join(['SELECT * FROM operation_rooms_info WHERE date==',str(date)]) # table of operation room capacities

op_df = pd.read_sql_query(query_op_cap, cnx)# operations room
op_df.index=op_df.room_name
op_df['room_capacity']=op_df['room_capacity'].astype(int)
op_df

,id,room_name,room_capacity,date
room_name,,,,
Room_1,Room_1-0feddaef-626b-4c51-b53f-21211f555e6e,Room_1,60,2022-02-19 00:00:00.000000
Room_2,Room_2-db4ada97-d0a7-42f5-a6f6-6e4408531847,Room_2,130,2022-02-19 00:00:00.000000
Room_3,Room_3-0636809c-ca2c-436b-9f28-c6e8ba18eab0,Room_3,95,2022-02-19 00:00:00.000000
Room_4,Room_4-2981aba7-f370-4e1e-98d8-7a233c85add4,Room_4,100,2022-02-19 00:00:00.000000
Room_5,Room_5-8b88d4b3-dd58-4fae-9e99-e81bf0a5abc3,Room_5,75,2022-02-19 00:00:00.000000

In [6]:
dep_df

,id,department_name,department_capacity,date
department_name,,,,
Department_1,Department_1-cab80d26-8a6d-43e2-9645-b8b53f42e22f,Department_1,120,2022-02-19 00:00:00.000000
Department_2,Department_2-d41e9e89-a121-469b-b4c7-9c9d1a0df0fe,Department_2,150,2022-02-19 00:00:00.000000
Department_3,Department_3-276f154b-f131-49dc-ba66-35a01991fb75,Department_3,80,2022-02-19 00:00:00.000000
Department_4,Department_4-1d316d13-732a-4c4a-b425-0973e54ab3ef,Department_4,60,2022-02-19 00:00:00.000000
Department_5,Department_5-56b8b4f0-0511-4a4a-ac58-00a96157ae25,Department_5,75,2022-02-19 00:00:00.000000

In [7]:
op_df['room_capacity'].dtype

dtype('int64')

In [8]:
dep_df['department_capacity']=dep_df['department_capacity'].astype(int)

In [9]:
basket

,id,doctor,operation_date,department_name,operation_duration,operation_urgency,operation_room
id,,,,,,,
Department_1-923716c6-cf97-4856-a996-4bea22397914,Department_1-923716c6-cf97-4856-a996-4bea22397914,Jack Bauer,2022-02-19 00:00:00.000000,Department_1,20,3,Room_5
Department_1-0704df1f-acac-4ab4-ac41-9d26bc326902,Department_1-0704df1f-acac-4ab4-ac41-9d26bc326902,Kurt Boz,2022-02-19 00:00:00.000000,Department_1,45,8,Room_1
Department_2-24a7b9a1-d766-4045-b180-7ff3f031cd02,Department_2-24a7b9a1-d766-4045-b180-7ff3f031cd02,Kurt,2022-02-19 00:00:00.000000,Department_2,23,1,Room_2
Department_5-22054592-a406-49bd-8ec0-1087784b0013,Department_5-22054592-a406-49bd-8ec0-1087784b0013,Norbert,2022-02-19 00:00:00.000000,Department_5,22,10,Room_2
Department_4-335326d6-cc07-44dd-bd65-311967a10167,Department_4-335326d6-cc07-44dd-bd65-311967a10167,Agatha,2022-02-19 00:00:00.000000,Department_4,44,6,Room_2
Department_3-d2365ebd-e4ec-4a26-98eb-c13e893ac6e5,Department_3-d2365ebd-e4ec-4a26-98eb-c13e893ac6e5,Kurt,2022-02-19 00:00:00.000000,Department_3,12,10,Room_1

In [10]:
basket['operation_duration'].dtype

dtype('int64')

In [11]:
# multi-knapsack, integer divisible

mdl = pyo.ConcreteModel()

# make sure id is also index in database user__entries
mdl.invs = pyo.Set(initialize=list(zip(basket.index, basket["department_name"])))
mdl.bins = pyo.Set(initialize=list(op_df.room_name)) ## list of operations room from db
mdl.deps = pyo.Set(initialize=list(dep_df.department_name)) # list of departments from db

# params
mdl.value   = pyo.Param(mdl.invs, initialize= {(i,row["department_name"]):row["operation_urgency"] for i,row in basket.iterrows()} )
mdl.weight  = pyo.Param(mdl.invs, initialize= {(i,row["department_name"]):row["operation_duration"] for i,row in basket.iterrows()})
mdl.bin_cap = pyo.Param(mdl.bins, initialize= {i:row["room_capacity"] for i,row in op_df.iterrows()} )
mdl.dep_cap = pyo.Param(mdl.deps, initialize= {i:row["department_capacity"] for i,row in dep_df.iterrows()}, mutable=True)



# vars
mdl.X = pyo.Var(mdl.invs, mdl.bins, within=pyo.Binary)     # the amount from invoice i in bin j



### Objective ###

mdl.OBJ = pyo.Objective(expr=sum(mdl.X[i, b]*mdl.value[i] for 
                        i in mdl.invs for
                        b in mdl.bins), sense=pyo.maximize)


### constraints ###

# don't overstuff bin
def bin_limit(self, b):
    return sum(mdl.X[i, b]*mdl.weight[i] for i in mdl.invs) <= mdl.bin_cap[b]
mdl.bin_limit = pyo.Constraint(mdl.bins, rule=bin_limit)

# one_item can be only in a single op room.
def one_item(self, i,d):
    return sum(mdl.X[i,d,b] for b in mdl.bins) <=1
mdl.one_item = pyo.Constraint(mdl.invs, rule=one_item)



# department limits

mdl.dep_limits=pyo.ConstraintList()

for d in mdl.deps:
    d_list=[]
    for i in mdl.X:
        if d==i[1]:
            d_list.append(i)    
    mdl.dep_limits.add(expr=(sum(mdl.X[i]*mdl.weight[i[:2]] for i in d_list)<=mdl.dep_cap[d])) 



# solve it...
solver = pyo.SolverFactory('glpk')
results = solver.solve(mdl)

In [12]:
results

{'Problem': [{'Name': 'unknown', 'Lower bound': 38.0, 'Upper bound': 38.0, 'Number of objectives': 1, 'Number of constraints': 17, 'Number of variables': 31, 'Number of nonzeros': 91, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '3', 'Number of created subproblems': '3'}}, 'Error rc': 0, 'Time': 0.020952224731445312}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [14]:
mdl.X.display()

X : Size=30, Index=X_index
    Key                                                                             : Lower : Value : Upper : Fixed : Stale : Domain
    ('Department_1-0704df1f-acac-4ab4-ac41-9d26bc326902', 'Department_1', 'Room_1') :     0 :   1.0 :     1 : False : False : Binary
    ('Department_1-0704df1f-acac-4ab4-ac41-9d26bc326902', 'Department_1', 'Room_2') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-0704df1f-acac-4ab4-ac41-9d26bc326902', 'Department_1', 'Room_3') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-0704df1f-acac-4ab4-ac41-9d26bc326902', 'Department_1', 'Room_4') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-0704df1f-acac-4ab4-ac41-9d26bc326902', 'Department_1', 'Room_5') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-923716c6-cf97-4856-a996-4bea22397914', 'Department_1', 'Room_1') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-923716c6-cf97-4856-a996-4bea22397914', 'Department_1', 'Room_2') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-923716c6-cf97-4856-a996-4bea22397914', 'Department_1', 'Room_3') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-923716c6-cf97-4856-a996-4bea22397914', 'Department_1', 'Room_4') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_1-923716c6-cf97-4856-a996-4bea22397914', 'Department_1', 'Room_5') :     0 :   1.0 :     1 : False : False : Binary
    ('Department_2-24a7b9a1-d766-4045-b180-7ff3f031cd02', 'Department_2', 'Room_1') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_2-24a7b9a1-d766-4045-b180-7ff3f031cd02', 'Department_2', 'Room_2') :     0 :   1.0 :     1 : False : False : Binary
    ('Department_2-24a7b9a1-d766-4045-b180-7ff3f031cd02', 'Department_2', 'Room_3') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_2-24a7b9a1-d766-4045-b180-7ff3f031cd02', 'Department_2', 'Room_4') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_2-24a7b9a1-d766-4045-b180-7ff3f031cd02', 'Department_2', 'Room_5') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_3-d2365ebd-e4ec-4a26-98eb-c13e893ac6e5', 'Department_3', 'Room_1') :     0 :   1.0 :     1 : False : False : Binary
    ('Department_3-d2365ebd-e4ec-4a26-98eb-c13e893ac6e5', 'Department_3', 'Room_2') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_3-d2365ebd-e4ec-4a26-98eb-c13e893ac6e5', 'Department_3', 'Room_3') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_3-d2365ebd-e4ec-4a26-98eb-c13e893ac6e5', 'Department_3', 'Room_4') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_3-d2365ebd-e4ec-4a26-98eb-c13e893ac6e5', 'Department_3', 'Room_5') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_4-335326d6-cc07-44dd-bd65-311967a10167', 'Department_4', 'Room_1') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_4-335326d6-cc07-44dd-bd65-311967a10167', 'Department_4', 'Room_2') :     0 :   1.0 :     1 : False : False : Binary
    ('Department_4-335326d6-cc07-44dd-bd65-311967a10167', 'Department_4', 'Room_3') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_4-335326d6-cc07-44dd-bd65-311967a10167', 'Department_4', 'Room_4') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_4-335326d6-cc07-44dd-bd65-311967a10167', 'Department_4', 'Room_5') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_5-22054592-a406-49bd-8ec0-1087784b0013', 'Department_5', 'Room_1') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_5-22054592-a406-49bd-8ec0-1087784b0013', 'Department_5', 'Room_2') :     0 :   1.0 :     1 : False : False : Binary
    ('Department_5-22054592-a406-49bd-8ec0-1087784b0013', 'Department_5', 'Room_3') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_5-22054592-a406-49bd-8ec0-1087784b0013', 'Department_5', 'Room_4') :     0 :   0.0 :     1 : False : False : Binary
    ('Department_5-22054592-a406-49bd-8ec0-1087784b0013', 'Department_5', 'Room_5') :     0 :   0.0 :     1 : False : False : Binary